[package]
name       = "rustic"
version    = "0.1.0"
edition    = "2018" # TODO: Update to 2021 editon when it's released in Oct.
publish    = false
license    = "AGPL-3.0-or-later"
authors    = ["MrArkon <mrarkon@outlook.com>"]
repository = "https://github.com/MrArkon/Rustic"

[dependencies]
once_cell         = "1.8.0"
pretty_env_logger = "0.4.0"
serenity          = "0.10.9"

[dependencies.config]
version          = "0.11.0"
default-features = false
features         = ["toml"]

[dependencies.log]
version            = "0.4.14"
features           = ["std", "serde"]

[dependencies.serde]
version = "1.0.130"
features = ["derive"]